[build]
  publish = "public"
  command = "./build.sh"

[build.environment]
  HUGO_VERSION = "0.147.7"
  HUGO_ENV = "production"
  HUGO_ENVIRONMENT = "production"

# Handle Hugo's clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Add custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 